#!/usr/bin/env python
import argparse
import socket
import select
import time
import json
import random

# ----------------------------- GLOBAL VARIABLES -----------------------------

SELF_ID = None # own ID
REPLICA_IDS = None # IDs of all other replicas

# ------------------------- END OF GLOBALS VARIABLES -------------------------

def connect():
    """Creates and connects a socket"""
    

def run():
    

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Key-Value Store.', 
                                     add_help=False)
    parser.add_argument('id',
                        help='ID of your replica (four-digit hex)')
    parser.add_argument('other_ids',
                        nargs='+',
                        help='IDs of all other replicas (four-digit hexs)')
    args = parser.parse_args()

    SELF_ID = args.id
    REPLICA_IDS = args.other_ids

    run()
